yesense_pub:
    ros__parameters:
        serial_port: "/dev/wheeltec_IMU"
        baud_rate: 460800
        frame_id: "imu_link"
        driver_type: "ros_serial"
        imu_topic_ros: "/sensors/imu/data"
        imu_topic: "/sensors/imu/data_raw"
